import './style.css'
import { Index } from './scripts/pages/index'
import { API, PhotographersApi } from './scripts/api/Api'
import { Photographer } from './scripts/models/Photographer'
import { PhotographerCard } from './scripts/templates/PhotographerCard'