import './style.css'
import { Index } from './scripts/pages/index'
import { PhotographerPage } from './scripts/pages/photographer'
import { API, PhotographersApi } from './scripts/api/Api'
import { Photographer } from './scripts/models/Photographer'
import { PhotographerCard } from './scripts/templates/PhotographerCard'
import { Media } from './scripts/models/Media'
import { PhotographersFactory } from './scripts/factories/PhotographersFactory' 
